Repository wantedPreOnboarding/19_07th_flowers, pull requests merged in 2022-02, with the labels that each got.

#9 [영종] Add - theme, popup(css, markup, open method)
  css/common/theme.css
  index.html
  js/components/popUp/popUp.js
  js/config/module.js
  js/main.js
  js/utils/cssUnits.js
  pages/popUp/assets/20220221_배송안내.png
  pages/popUp/js/main.js
  pages/popUp/popup.css
  pages/popUp/popup.html
Labels: enhancement

#10 [수임] Add - #3 slide style 추가
  assets/kukka.png
  css/common/index.css
  css/common/theme.css
  css/components/banner.css
  css/components/index.css
  css/components/slide.css
  css/config/index.css
  css/config/reset.css
  css/index.css
  css/layout/index.css
  index.html
  js/components/popUp/popUp.js
  js/config/module.js
  js/consts.js
  js/consts/breakPoints.js
  js/main.js
  js/utils/cssUnits.js
  pages/popUp/assets/20220221_배송안내.png
  pages/popUp/js/main.js
  pages/popUp/popup.css
  pages/popUp/popup.html
Labels: style

#12 [송현] Add - PC footer 레이아웃
  css/components/footer.css
  css/components/index.css
  css/index.css
  index.html
Labels: style

#11 [다빈] Add - 네비게이션 구현
  css/components/header/index.css
  css/components/index.css
  css/components/nav/index.css
  index.html
  js/components/header/header.js
  js/components/nav/nav.js
  robots.txt
Labels: enhancement, style

#18 [수임] Add - 슬라이드 미디어 쿼리 적용 및 버튼 클릭 이벤트 적용
  assets/slide_image0.jpeg
  assets/slide_image1.jpeg
  assets/slide_image2.jpeg
  css/components/index.css
  css/components/slide.css
  index.html
  js/components/slide/slide.js
  js/consts/breakPoints.js
Labels: enhancement, style

#21 Modify 슬라이드 이미지 호버 수정
  css/components/slide.css
  index.html
  js/components/slide/slide.js
Labels: style

#23 Add 슬라이드 링크 추가 및 modify 헤더 이동 애니메이션 선택 element 수정
  assets/base.png
  assets/slide_image0.jpeg
  assets/slide_image1.jpeg
  assets/slide_image2.jpeg
  css/common/theme.css
  css/components/banner.css
  css/components/footer.css
  css/components/header/index.css
  css/components/index.css
  css/components/nav/index.css
  css/components/slide.css
  css/index.css
  index.html
  js/components/banner/banner.js
  js/components/footer/footer.js
  js/components/header/header.js
  js/components/nav/nav.js
  js/components/popUp/popUp.js
  js/components/slide/slide.js
  js/config/module.js
  js/consts/breakPoints.js
  js/main.js
  pages/popUp/index.html
  pages/popUp/js/main.js
  pages/popUp/js/slideIndexManager.js
  pages/popUp/popup.css
  robots.txt
Labels: enhancement
